### ISSUE TITLE
Hvorfor ikke dokumentasjon på norsk?

### ISSUE THREAD

**Issue by Kyrremann** [navikt/nav-java-codestyle#2]
Hvorfor er ikke repoet på norsk? Er i navikt-domenet, og NAV sitt "morsmål" er jo norsk.

**Comment by tlheen** [comment]
Du tenker nav-java-kodeformat, nav-java-kodestil eller lignende @Kyrremann ?

Jeg er tilhenger av norsk når domenet er norsk, men samtidig engelsk for begreper som henspeiler til patterns eller andre godt innarbeide fagbegreper.

I denne kontekst så tror jeg Codestyle er lettere å forstå (fordi det er domenespråket her), enn alternativene jeg prøvde meg på.

**Comment by Kyrremann** [comment]
Var litt uklar, mente Readmeen, greit st vi bruker codestyle som begrep.

**Comment by eirslett** [comment]
Hvis vi skriver på norsk, så er det vanskeligere for internasjonale brukere. NAV på Github har jo et potensielt internasjonalt nedslagsfelt. Så nais utvikles på engelsk.

For mange legacy-kodebaser i NAV så er jo koden allerede skrevet på norsk fra før, der er det for sent, men generelt sett så er det dumt å utestenge de 99 % av utviklerne i verden som ikke kan norsk.

**Comment by Kyrremann** [comment]
Jeg kan være enig med deg at `nais` skal være på engelsk, men syns ikke vi bør spisse `navikt` til å være på engelsk. Greit nok er det vanskeligere for internasjonale brukere, men vi er en norsk etat, rettet mot norske brukere, som skal tilby tjenestene på norsk. Jeg mener også at nordmenn flest er flinkere til å uttrykke seg på norsk, enn på engelsk (ingen data på det akkurat nå).

Og, hvis argumentet ditt er at folk ikke kan norsk, så burde vi vel egentlig spisse oss inn på spansk eller kinesisk (https://www.ethnologue.com/statistics/size), men blir jo vanskelig når de færreste av oss kan det.

**Comment by Kyrremann** [comment]
Grunnen til at jeg reagerer på denne, er at jeg føler dette er dokumentasjon som hovedsaklig NAV-utviklere skal forholde seg til, altså ikke et produkt (som `nais`), hvor vi tror/håper andre kan ha nytte av.

**Comment by Muni10** [comment]
Det er vel ikke nødvendigvis bare utenfor NAV utviklere er mer komfortable med engelsk heller. Hvis man ikke greier skrive dok på engelsk får man heller bare få hjelp til det da.

**Comment by eirslett** [comment]
Generelt sett; open-source-verden foregår på engelsk. Det er de-facto-fagspråket i bransjen. Alle utviklere i NAV forstår og kan skrive engelsk, spesielt på fagspråk. En del utviklere kan formulere seg bedre på engelsk enn på norsk, for en del av faguttrykkene er jo it utgangspunktet engelske. Man unngår klønete norwenglish-formuleringer eller forvirring mellom norske oversettelser av uttrykkene. Det er veldig lite open-source som foregår på spansk eller kinesisk (bare Vue som jeg vet om), men vi i NAV kan jo ikke de språkene, så det ville vært et håpløst prosjekt ha det som dokumentasjonsspråk!

Ingen har sagt at alle prosjekter i `navikt`-organisasjonen skal være på engelsk, men det er jo noen av prosjektene det er mer naturlig for enn andre. Hvis det er greenfield-prosjekt, og ikke involverer NAV-faguttrykk, så ser jeg ingen grunn til å ikke bruke engelsk.

Jeg vil tro en stor andel av utviklerne i NAV har bakgrunn fra andre prosjekter de både koder og dokumenterer på engelsk. Selv "rene norske" selskaper som FINN.no gjør det. Det gjør det også mulig å ansette utviklere med norsk som andrespråk.

Det er helt riktig at vi har norske brukere og skal tilby brukerne en tjeneste på norsk, men da er det jo snakk om forretningsapplikasjonene sine brukergrensesnitt. Fellesbibliotek er noe annet.

Angående nais, så er jo også det i realiteten NAV-spesifikt, det har en obligatorisk avhengiget på fasit, som er et internt verktøy og ikke er en del av nais. Sånn sett så er jo kodestilen vår _mer_ gjenbrukbar enn nais-prosjektet. Og det er klart utviklere utenfor NAV kan ha nytte av å se hvordan vi gjør kodestil her på huset. Hva er problemet?

**Comment by eirslett** [comment]
Kodestil er også noe folk diskuterer og bruker på tvers av selskaper. For eksempel [airbnb](https://github.com/airbnb/javascript) sin eslint-config, med 69.000 stjerner på Github, som er tatt i bruk i veldig mange andre open-source-prosjekter og in-house-kodebaser i helt andre selskaper. Jeg sier ikke at NAV sin kodestil skal bli det neste airbnb, men at domenet i prinsippet ikke er NAV-spesifikt eller norsk i noen større grad enn for eksempel nais.

**Comment by Kyrremann** [comment]
Bare for å runde av samtalen, min tanke kan enklest summeres opp i at vi er en norsk etat, og da bør vi prøve å ha ting på norsk.
